// Typed loader for the GMS v270 item catalogue, and the upgrade-capability
// resolver the analysis engine asks before it proposes anything.
//
// WHY THIS EXISTS
// ---------------
// `candidates.ts` used to trust whatever gear an agent PUT at it, so it happily
// proposed impossible upgrades: star forcing a Ring of Restraint (which has no
// upgrade slots), star forcing a Genesis weapon (which is granted at a fixed
// 22★), flaming a ring (rings never take bonus stats). The catalogue is the
// ground truth those questions are answered against.
//
// The data lives in `catalogue.json`, generated by
// `scripts/build-item-catalogue.mjs` from maplestory.io GMS/270 plus the pinned
// `chablades/mapledoro` v270 manifests. DO NOT hand-edit the JSON — regenerate it.
//
// The rules themselves, and their citations, are in `rules.ts`.
//
// LOOKUP CONTRACT
// ---------------
//  * Lookup is by item NAME, case- and whitespace-insensitive, because a name is
//    all a tooltip screenshot reliably gives us. Item ids are not on tooltips.
//  * Several distinct items share one in-game name (three "Silver Blossom Ring"
//    ids, two "Destiny Shining Rod" stages). A name that resolves to several
//    entries is merged PERMISSIVELY: a capability is denied only when EVERY
//    entry with that name denies it. Suppressing an upgrade is a destructive
//    act, so we only do it when the catalogue is unanimous.
//  * An item NOT in the catalogue is never silently dropped. It falls back to
//    the slot/category rules only — which are certain — and is flagged
//    `known: false` with an `unknown-item` reason so the UI can say
//    "unrecognised item" rather than "no upgrades available".
//
// COVERAGE — READ THIS BEFORE TRUSTING AN ABSENCE
// ----------------------------------------------
// The dump is GMS **v270**, the newest maplestory.io serves (v271-v278 all
// return 500/502, and there is no `latest` alias). v270 PREDATES the Anima
// class **Ren**, so "Imugi Gem" — Ren's secondary — is genuinely not in here,
// and neither are Mo Xuan's, Sia Astelle's or Erel Light's weapons, nor Kanna's
// v266 Talisman. See `CATALOGUE_META.coverage`.
//
// Therefore: **absence is UNKNOWN, never INVALID.** `capabilities()` never
// infers a restriction from a name it could not find — it falls through to the
// SLOT rules, which are independently verified across the whole v270 dump (0 of
// 316 medals, 0 of 239 androids, 0 of 102 totems and 0 of 59 pocket items have
// any upgrade slots), and flags the item `known: false`. A weapon or secondary
// whose name is unknown keeps every capability, so a Ren main is advised
// normally rather than being told its gear does not exist.

import * as starforce from '$lib/data/starforce';

import raw from './catalogue.json';
import { RULES, reasonsFor, type RuleId } from './rules';

export { RULES, RULE_IDS, reasonsFor, type RuleDoc, type RuleId } from './rules';

/* -------------------------------------------------------------------------- */
/* Types                                                                       */
/* -------------------------------------------------------------------------- */

/**
 * Canonical slot family. Coarser than `schema.Slot` (there is one `ring`, not
 * `ring1..ring4`) because an item's capabilities do not depend on which of the
 * four ring slots it happens to sit in.
 */
export type CatalogueSlot =
	| 'weapon'
	| 'secondary'
	| 'emblem'
	| 'hat'
	| 'top'
	| 'bottom'
	| 'overall'
	| 'shoes'
	| 'gloves'
	| 'cape'
	| 'shoulder'
	| 'belt'
	| 'pendant'
	| 'ring'
	| 'earrings'
	| 'face'
	| 'eye'
	| 'pocket'
	| 'badge'
	| 'medal'
	| 'heart'
	| 'android'
	| 'totem';

/**
 * One catalogue item.
 *
 * `category`, `canBonusPotential` and `iconUrl` are DERIVED at load and are not
 * in the JSON — storing them cost ~640 KB across 5,700 entries in a file that
 * ships in the bundle. Consumers see them exactly as if they were stored.
 */
export interface CatalogueEntry {
	id: number;
	name: string;
	slot: CatalogueSlot;
	/** Derived. The `ItemCategory` from `src/lib/schema/item.ts`. */
	category: string;
	/** REQ LEV / base item level. */
	itemLevel: number;
	/** In-game weapon-type label ("Two-Handed Sword", "Bow", "Claw", ...). */
	weaponType?: string;
	/** Occupies the secondary slot as well as the weapon slot. */
	twoHanded?: boolean;
	setItemId?: number;
	setName?: string;
	/**
	 * RAW WZ `tuc`. mapledoro's own `_meta` warns "in-game upgrade slots equal
	 * tuc plus 1" — we never display it, we only ask whether it is 0, which is
	 * the "this item has no upgrade slots at all" signal.
	 */
	upgradeSlots: number;
	/** Derived from `CATALOGUE_META.sources.iconTemplate`. */
	iconUrl: string;

	canStarforce: boolean;
	fixedStarforce?: number;
	canFlame: boolean;
	canPotential: boolean;
	/** Derived: bonus potential requires regular potential, so it tracks `canPotential`. */
	canBonusPotential: boolean;
	superior?: boolean;
	superiorMaxStars?: number;
	rules: string[];
}

export interface CatalogueCoverage {
	/** Prose warning about what this dump cannot contain. Safe to show a user. */
	note: string;
	/** Named things released after v270 that will never resolve. */
	knownMissing: string[];
	/** What happened when newer GMS versions were probed. */
	newerVersionsProbed: string;
}

export interface CatalogueMeta {
	generatedAt: string;
	region: string;
	gameVersion: string;
	minItemLevel: number;
	/** What this dump is missing, and why an absent name must mean "unknown". */
	coverage: CatalogueCoverage;
	sources: Record<string, string>;
	counts: Record<string, number>;
}

export interface ItemCapabilities {
	canStarforce: boolean;
	canFlame: boolean;
	canPotential: boolean;
	canBonusPotential: boolean;
	/** Set when the item comes at a star count that cannot be changed (Genesis / Destiny = 22). */
	fixedStarforce?: number;
	/** Highest reachable star count. Absent when the item takes no star force at all. */
	maxStarforce?: number;
	superior?: boolean;
	/** False when the item name could not be resolved to any catalogue entry. */
	known: boolean;
	/** How the name resolved: exact catalogue hit, a fuzzy same-slot hit, or nothing. */
	matchQuality: NameMatch;
	/** The catalogue entries the name resolved to, in id order. Empty when unknown. */
	entries: readonly CatalogueEntry[];
	/** `{ ruleId: human-readable reason }` for every rule that fired. */
	reasons: Record<string, string>;
	/**
	 * The rule ids that actually blocked each capability, so a caller can print
	 * "why is there no star force candidate" WITHOUT also printing the unrelated
	 * flame and bonus-potential rules. Empty when the capability is allowed.
	 */
	blockedBy: Record<'starforce' | 'flame' | 'potential' | 'bonusPotential', string[]>;
	/** Set when a liberated-weapon family rule decided this item ("Genesis", "Destiny", ...). */
	family?: string;
}

/** Which rule ids are evidence for which capability being blocked. */
const BLOCKING_RULES: Record<
	'starforce' | 'flame' | 'potential' | 'bonusPotential',
	readonly string[]
> = {
	starforce: [
		'liberated-weapon-fixed-star',
		'destiny-stage-ambiguous',
		'sealed-liberation-weapon',
		'no-upgrade-slots',
		'exclusive-scroll-only',
		'superior-equipment'
	],
	flame: ['flame-ineligible-slot'],
	potential: ['potential-ineligible-slot'],
	bonusPotential: ['bonus-potential-not-in-heroic']
};

/** The subset of `schema.Item` this module needs. */
export interface CapabilityQuery {
	name: string;
	/** `ItemCategory` from the schema; used for the unknown-item fallback. */
	category?: string;
	/** `Slot` from the schema (`ring1`, `totem2`, ...); used for the unknown-item fallback. */
	slot?: string;
	itemLevel?: number;
	/** User-confirmed Tyrant/Nova/Elite Heliseum flag, if the catalogue does not know. */
	superior?: boolean;
}

/* -------------------------------------------------------------------------- */
/* The catalogue                                                               */
/* -------------------------------------------------------------------------- */

const doc = raw as unknown as CatalogueMeta & {
	entries: (Omit<CatalogueEntry, 'category' | 'canBonusPotential' | 'iconUrl' | 'rules'> & {
		rules?: string[];
	})[];
};

/** Our canonical slot family -> the `ItemCategory` in `src/lib/schema/item.ts`. */
const SLOT_TO_CATEGORY: Record<CatalogueSlot, string> = {
	weapon: 'weapon',
	secondary: 'secondary',
	emblem: 'emblem',
	hat: 'armor',
	top: 'armor',
	bottom: 'armor',
	overall: 'armor',
	shoes: 'armor',
	gloves: 'armor',
	cape: 'armor',
	shoulder: 'armor',
	belt: 'accessory',
	pendant: 'accessory',
	ring: 'accessory',
	earrings: 'accessory',
	face: 'accessory',
	eye: 'accessory',
	pocket: 'pocket',
	badge: 'badge',
	medal: 'medal',
	heart: 'heart',
	android: 'android',
	totem: 'totem'
};

const ICON_TEMPLATE = doc.sources.iconTemplate;

export const CATALOGUE: readonly CatalogueEntry[] = doc.entries.map((entry) => ({
	...entry,
	category: SLOT_TO_CATEGORY[entry.slot],
	canBonusPotential: entry.canPotential,
	iconUrl: ICON_TEMPLATE.replace('{id}', String(entry.id)),
	rules: entry.rules ?? []
}));

export const CATALOGUE_META: CatalogueMeta = {
	generatedAt: doc.generatedAt,
	region: doc.region,
	gameVersion: doc.gameVersion,
	minItemLevel: doc.minItemLevel,
	coverage: doc.coverage,
	sources: doc.sources,
	counts: doc.counts
};

/** Lowercase, whitespace-collapsed, punctuation-normalised item name. */
export function normalizeItemName(name: string): string {
	return name
		.normalize('NFKC')
		.replace(/[‘’ʼ]/g, "'")
		.replace(/[–—]/g, '-')
		.trim()
		.replace(/\s+/g, ' ')
		.toLowerCase();
}

const BY_NAME = new Map<string, CatalogueEntry[]>();
const BY_ID = new Map<number, CatalogueEntry>();
for (const entry of CATALOGUE) {
	BY_ID.set(entry.id, entry);
	const key = normalizeItemName(entry.name);
	const bucket = BY_NAME.get(key);
	if (bucket) bucket.push(entry);
	else BY_NAME.set(key, [entry]);
}

export type NameMatch = 'exact' | 'approximate' | 'none';

/**
 * Trailing nouns that a capture often appends but the real item name omits:
 * "Total Control Heart" is really "Total Control", "Arcane Umbra Hat" is really
 * "Arcane Umbra Knight Hat". Stripping the trailing slot noun and retrying is a
 * cheap way to turn a miss into a hit.
 */
const TRAILING_SLOT_NOUNS: Record<string, readonly string[]> = {
	heart: ['heart'],
	ring: ['ring'],
	badge: ['badge'],
	medal: ['medal'],
	android: ['android'],
	totem: ['totem'],
	emblem: ['emblem'],
	pocket: ['pocket'],
	shoulder: ['shoulder'],
	belt: ['belt'],
	pendant: ['pendant'],
	earrings: ['earrings', 'earring'],
	cape: ['cape'],
	gloves: ['gloves', 'glove'],
	shoes: ['shoes', 'shoe'],
	hat: ['hat', 'helm', 'cap'],
	overall: ['overall'],
	top: ['top'],
	bottom: ['bottom']
};

/** Every catalogue entry sharing an in-game name. Empty when the name is unknown. */
export function findByName(name: string): readonly CatalogueEntry[] {
	return BY_NAME.get(normalizeItemName(name)) ?? [];
}

/**
 * Resolve a captured item name to catalogue entries.
 *
 * Captures are made from tooltip screenshots, so names arrive approximated
 * ("Arcane Umbra Hat" for "Arcane Umbra Knight Hat", "AbsoLab Shoulder" for
 * "AbsoLab Knight Shoulder", "Total Control Heart" for "Total Control"). Three
 * passes, most specific first:
 *   1. exact, on the normalised name;
 *   2. exact, after dropping a trailing slot noun;
 *   3. token-superset within the same slot — every token of the query appears
 *      in the candidate's name. Needs at least two query tokens so that a bare
 *      "Ring" cannot match 184 rings.
 * Pass 3 is reported as `approximate` so the caller can flag it.
 */
export function resolveByName(
	name: string,
	slot?: CatalogueSlot
): { entries: CatalogueEntry[]; match: NameMatch } {
	const key = normalizeItemName(name);

	const exact = BY_NAME.get(key);
	if (exact) return { entries: exact, match: 'exact' };

	const tokens = key.split(' ').filter(Boolean);
	if (slot && tokens.length > 1) {
		const nouns = TRAILING_SLOT_NOUNS[slot] ?? [];
		if (nouns.includes(tokens[tokens.length - 1])) {
			const stripped = BY_NAME.get(tokens.slice(0, -1).join(' '));
			if (stripped) return { entries: stripped, match: 'exact' };
		}
	}

	if (tokens.length < 2) return { entries: [], match: 'none' };
	const pool = slot ? CATALOGUE.filter((e) => e.slot === slot) : CATALOGUE;
	const fuzzy = pool.filter((entry) => {
		const words = normalizeItemName(entry.name).split(' ');
		return tokens.every((token) => words.includes(token));
	});
	if (fuzzy.length > 0) return { entries: fuzzy, match: 'approximate' };
	return { entries: [], match: 'none' };
}

/* -------------------------------------------------------------------------- */
/* Liberated-weapon families                                                   */
/*                                                                             */
/* Genesis and Destiny weapons are per-class, so there are dozens of names      */
/* ("Genesis Bow", "Genesis Bladecaster", "Destiny Shining Rod", ...) and a     */
/* capture may well produce a generic one ("Genesis Sword", "Genesis Fan") that */
/* is not a real item id at all. A NAME-FAMILY rule is therefore the primary    */
/* mechanism here, not the per-id catalogue flags: it fires on the prefix,      */
/* regardless of whether the exact name is in the v270 dump.                    */
/*                                                                             */
/* Anchored at the start of the name AND restricted to the weapon slot, so it   */
/* cannot capture the Genesis Badge, the Genesis Bandana (a hat), the "Bond of  */
/* Destiny" cape or the four "…Destiny" medals — all of which a bare substring  */
/* match on "genesis"/"destiny" would wrongly hit.                              */
/* -------------------------------------------------------------------------- */

export interface LiberatedWeaponFamily {
	/** Matched against the normalised (lowercase) item name. */
	prefix: RegExp;
	label: string;
	/** The star count the weapon is granted at, when it has one. */
	fixedStarforce?: number;
	rules: readonly RuleId[];
}

export const LIBERATED_WEAPON_FAMILIES: readonly LiberatedWeaponFamily[] = [
	{
		// Must be tested BEFORE the bare `genesis` prefix.
		prefix: /^sealed genesis\b/,
		label: 'Sealed Genesis',
		rules: ['sealed-liberation-weapon', 'no-upgrade-slots']
	},
	{
		prefix: /^genesis\b/,
		label: 'Genesis',
		fixedStarforce: 22,
		rules: ['liberated-weapon-fixed-star']
	},
	{
		prefix: /^destiny\b/,
		label: 'Destiny',
		fixedStarforce: 22,
		rules: ['liberated-weapon-fixed-star', 'destiny-stage-ambiguous']
	}
];

/**
 * The liberated-weapon family for an item, or `undefined`.
 * Only ever applies to the WEAPON slot.
 */
export function liberatedWeaponFamily(
	name: string,
	slot: CatalogueSlot | undefined,
	category?: string
): LiberatedWeaponFamily | undefined {
	if (slot !== 'weapon' && category !== 'weapon') return undefined;
	const key = normalizeItemName(name);
	return LIBERATED_WEAPON_FAMILIES.find((family) => family.prefix.test(key));
}

export function findById(id: number): CatalogueEntry | undefined {
	return BY_ID.get(id);
}

/* -------------------------------------------------------------------------- */
/* Slot rules, for items the catalogue does not know                           */
/* -------------------------------------------------------------------------- */

/** `schema.Slot` (`ring1`, `totem2`, ...) -> `CatalogueSlot`. */
export function catalogueSlot(slot: string | undefined): CatalogueSlot | undefined {
	if (!slot) return undefined;
	const base = slot.replace(/\d+$/, '');
	if (base === 'pendant' || base === 'ring' || base === 'totem') return base as CatalogueSlot;
	return (
		[
			'weapon',
			'secondary',
			'emblem',
			'hat',
			'top',
			'bottom',
			'overall',
			'shoes',
			'gloves',
			'cape',
			'shoulder',
			'belt',
			'earrings',
			'face',
			'eye',
			'pocket',
			'badge',
			'medal',
			'heart',
			'android'
		] as const
	).find((s) => s === base);
}

/**
 * Slot families that never take star force, independent of any single item.
 * Verified against the v270 catalogue: every medal (316 at Lv100+), every
 * emblem, every pocket item, every totem, every android and every non-weapon
 * secondary has zero upgrade slots. Badges are ALMOST in this list — Ghost Ship
 * Exorcist and the Sengoku Hakase Badge are the only two that enhance — so
 * `badge` is deliberately absent and is decided per item instead.
 * Hearts / mechanical hearts DO take star force and are also absent.
 */
export const NEVER_STAR_FORCE_SLOTS: readonly CatalogueSlot[] = [
	'emblem',
	'medal',
	'pocket',
	'totem',
	'android'
];

/** formulas.md §4A §2.1. See `rules.ts` for the citation. */
export const NEVER_FLAME_SLOTS: readonly CatalogueSlot[] = [
	'secondary',
	'emblem',
	'badge',
	'medal',
	'ring',
	'android',
	'heart',
	'shoulder',
	'totem'
	// `pocket` is NOT here: pocket items are absent from the wiki's and
	// formulas.md §4A §2.1's "cannot receive bonus stats" lists, and the Pink
	// Holy Cup is a Boss Reward item that does get bonus stats.
];

/** formulas.md §4A §3.1. See `rules.ts` for the citation. */
export const NEVER_POTENTIAL_SLOTS: readonly CatalogueSlot[] = [
	'medal',
	'badge',
	'pocket',
	'android',
	'totem'
];

/* -------------------------------------------------------------------------- */
/* capabilities()                                                              */
/* -------------------------------------------------------------------------- */

/**
 * Per-item max-star exceptions that are NOT the Genesis/Destiny fixed-star
 * case. Taken from `starforce.MAX_STAR_EXCEPTIONS`, minus its `genesis` and
 * `destiny` rows: those match on a bare substring, which also captures the
 * Genesis Badge, the Genesis Bandana, the "Bond of Destiny" cape and four
 * "…Destiny" medals. The catalogue resolves the real weapons by id, so this
 * module handles them itself and only borrows the unambiguous rows.
 */
const NAMED_MAX_STAR_EXCEPTIONS = starforce.MAX_STAR_EXCEPTIONS.filter(
	(row) => !('fixed' in row && row.fixed)
);

function namedMaxStars(name: string): number | undefined {
	const lower = normalizeItemName(name);
	for (const row of NAMED_MAX_STAR_EXCEPTIONS) {
		if (lower.includes(row.match)) return row.maxStars;
	}
	return undefined;
}

/**
 * What this item can and cannot have done to it.
 *
 * Resolution order:
 *   1. Catalogue lookup by normalised name. If several entries share the name,
 *      capabilities are merged permissively (deny only when unanimous).
 *   2. If the name is unknown, fall back to the slot/category rules alone and
 *      flag `known: false`. This is deliberately permissive: an unrecognised
 *      item must still generate candidates, or a typo would silently delete a
 *      real upgrade from the ranking.
 */
export function capabilities(item: CapabilityQuery): ItemCapabilities {
	// `capabilities` is pure and the analysis calls it several times per item
	// (star force, flames, potential, the gear summary), and a miss walks all
	// 5,691 entries for the fuzzy pass. Memoise on the whole query.
	const cacheKey = [
		item.name,
		item.slot ?? '',
		item.category ?? '',
		item.itemLevel ?? '',
		item.superior ? '1' : ''
	].join('\u0000');
	const cached = CAPABILITY_CACHE.get(cacheKey);
	if (cached) return cached;

	const result = computeCapabilities(item);
	CAPABILITY_CACHE.set(cacheKey, result);
	return result;
}

const CAPABILITY_CACHE = new Map<string, ItemCapabilities>();

function computeCapabilities(item: CapabilityQuery): ItemCapabilities {
	const querySlot = catalogueSlot(item.slot) ?? categoryToSlot(item.category);
	const resolved = resolveByName(item.name, querySlot);
	const entries = resolved.entries;
	const ruleIds: string[] = [];

	const slot = entries.length > 0 ? entries[0].slot : querySlot;
	if (resolved.match === 'approximate') ruleIds.push('approximate-name-match');

	let canStarforce: boolean;
	let canFlame: boolean;
	let canPotential: boolean;
	let canBonusPotential: boolean;
	let fixedStarforce: number | undefined;
	let superior = item.superior === true;
	let superiorMaxStars: number | undefined;

	if (entries.length > 0) {
		// Permissive merge: deny only when every entry with this name denies.
		canStarforce = entries.some((e) => e.canStarforce);
		canFlame = entries.some((e) => e.canFlame);
		canPotential = entries.some((e) => e.canPotential);
		canBonusPotential = entries.some((e) => e.canBonusPotential);
		superior = superior || entries.some((e) => e.superior === true);

		const fixed = new Set(
			entries.map((e) => e.fixedStarforce).filter((v): v is number => v !== undefined)
		);
		if (fixed.size === 1 && entries.every((e) => e.fixedStarforce !== undefined)) {
			fixedStarforce = [...fixed][0];
		}

		const caps = entries.map((e) => e.superiorMaxStars).filter((v): v is number => v !== undefined);
		if (caps.length > 0) superiorMaxStars = Math.max(...caps);

		for (const entry of entries) {
			for (const id of entry.rules) if (!ruleIds.includes(id)) ruleIds.push(id);
		}
		// A rule only earns its reason if it actually bit after the merge.
		if (canStarforce) {
			for (const id of [
				'no-upgrade-slots',
				'liberated-weapon-fixed-star',
				'destiny-stage-ambiguous'
			]) {
				const at = ruleIds.indexOf(id);
				if (at >= 0) ruleIds.splice(at, 1);
			}
		}
		if (canFlame) drop(ruleIds, 'flame-ineligible-slot');
		if (canPotential) drop(ruleIds, 'potential-ineligible-slot');
	} else {
		ruleIds.push('unknown-item');
		canStarforce = slot === undefined || !NEVER_STAR_FORCE_SLOTS.includes(slot);
		canFlame = slot === undefined || !NEVER_FLAME_SLOTS.includes(slot);
		canPotential = slot === undefined || !NEVER_POTENTIAL_SLOTS.includes(slot);
		canBonusPotential = canPotential;
		if (!canStarforce) ruleIds.push('no-upgrade-slots');
		if (!canFlame) ruleIds.push('flame-ineligible-slot');
		if (!canPotential) ruleIds.push('potential-ineligible-slot');
	}

	// Bonus potential does not exist in Heroic — the only world scope modelled.
	if (canBonusPotential) ruleIds.push('bonus-potential-not-in-heroic');
	canBonusPotential = false;

	// The liberated-weapon family rule OVERRIDES everything above. It is keyed on
	// the name prefix rather than on a catalogue id, because Genesis and Destiny
	// weapons are per-class (dozens of names) and a capture may produce a generic
	// one — "Genesis Sword", "Genesis Fan" — that no catalogue id carries.
	const family = liberatedWeaponFamily(item.name, slot, item.category);
	if (family) {
		// The family rule is authoritative, so an approximate name hit is no longer
		// interesting: "Genesis Sword" was recognised, just not as one exact id.
		drop(ruleIds, 'approximate-name-match');
		canStarforce = false;
		fixedStarforce = family.fixedStarforce;
		for (const id of [
			'no-upgrade-slots',
			'liberated-weapon-fixed-star',
			'destiny-stage-ambiguous',
			'sealed-liberation-weapon'
		]) {
			drop(ruleIds, id);
		}
		ruleIds.push(...family.rules);
	}

	/* --- max stars -------------------------------------------------------- */
	const itemLevel = item.itemLevel ?? entries[0]?.itemLevel;
	let maxStarforce: number | undefined;
	if (fixedStarforce !== undefined) {
		maxStarforce = fixedStarforce;
	} else if (canStarforce && itemLevel !== undefined) {
		maxStarforce = starforce.maxStars(itemLevel, superior);
		const named = namedMaxStars(item.name);
		if (named !== undefined) maxStarforce = Math.min(maxStarforce, named);
		if (superiorMaxStars !== undefined) maxStarforce = Math.min(maxStarforce, superiorMaxStars);
	}

	// Only report a rule as "blocking" X when X is actually blocked, and only
	// report the rules that bear on X — printing every rule that fired made the
	// star force note also explain flames and bonus potential.
	const unrecognised = entries.length === 0 ? ['unknown-item'] : [];
	const blockedFor = (
		key: 'starforce' | 'flame' | 'potential' | 'bonusPotential',
		blocked: boolean
	): string[] => {
		if (!blocked) return [];
		const own = ruleIds.filter((id) => BLOCKING_RULES[key].includes(id));
		return [...own, ...unrecognised.filter((id) => ruleIds.includes(id))];
	};

	return {
		canStarforce,
		canFlame,
		canPotential,
		canBonusPotential,
		...(fixedStarforce !== undefined ? { fixedStarforce } : {}),
		...(maxStarforce !== undefined ? { maxStarforce } : {}),
		...(superior ? { superior: true } : {}),
		known: entries.length > 0,
		matchQuality: resolved.match,
		entries,
		reasons: reasonsFor(ruleIds),
		blockedBy: {
			starforce: blockedFor('starforce', !canStarforce),
			flame: blockedFor('flame', !canFlame),
			potential: blockedFor('potential', !canPotential),
			bonusPotential: blockedFor('bonusPotential', !canBonusPotential)
		},
		...(family ? { family: family.label } : {})
	};
}

function drop(ids: string[], id: string): void {
	const at = ids.indexOf(id);
	if (at >= 0) ids.splice(at, 1);
}

/** Last-resort slot guess from the schema `ItemCategory` when no slot was given. */
function categoryToSlot(category: string | undefined): CatalogueSlot | undefined {
	switch (category) {
		case 'weapon':
		case 'secondary':
		case 'emblem':
		case 'heart':
		case 'badge':
		case 'pocket':
		case 'medal':
		case 'android':
		case 'totem':
			return category;
		// `armor` and `accessory` span several slot families with different
		// rules (a ring takes no flames, a belt does), so there is nothing safe
		// to guess — return undefined and let the fallback stay permissive.
		default:
			return undefined;
	}
}

/** The single reason string for one rule id, for callers that want just the prose. */
export function ruleReason(id: RuleId): string {
	return RULES[id].reason;
}
