// Typed loader for the GMS v270 item catalogue, and the upgrade-capability
// resolver the analysis engine asks before it proposes anything.
//
// WHY THIS EXISTS
// ---------------
// `candidates.ts` used to trust whatever gear an agent PUT at it, so it happily
// proposed impossible upgrades: star forcing a Ring of Restraint (which has no
// upgrade slots), star forcing a Genesis weapon (which is granted at a fixed
// 22★), flaming a ring (rings never take bonus stats). The catalogue is the
// ground truth those questions are answered against.
//
// The data lives in `catalogue.json`, generated by
// `scripts/build-item-catalogue.mjs` from maplestory.io GMS/270 plus the pinned
// `chablades/mapledoro` v270 manifests. DO NOT hand-edit the JSON — regenerate it.
//
// The rules themselves, and their citations, are in `rules.ts`.
//
// LOOKUP CONTRACT
// ---------------
//  * Lookup is by item NAME, case- and whitespace-insensitive, because a name is
//    all a tooltip screenshot reliably gives us. Item ids are not on tooltips.
//  * Several distinct items share one in-game name (three "Silver Blossom Ring"
//    ids, two "Destiny Shining Rod" stages). A name that resolves to several
//    entries is merged PERMISSIVELY: a capability is denied only when EVERY
//    entry with that name denies it. Suppressing an upgrade is a destructive
//    act, so we only do it when the catalogue is unanimous.
//  * An item NOT in the catalogue is never silently dropped. It falls back to
//    the slot/category rules only — which are certain — and is flagged
//    `known: false` with an `unknown-item` reason so the UI can say
//    "unrecognised item" rather than "no upgrades available".

import * as starforce from '$lib/data/starforce';

import raw from './catalogue.json';
import { RULES, reasonsFor, type RuleId } from './rules';

export { RULES, RULE_IDS, reasonsFor, type RuleDoc, type RuleId } from './rules';

/* -------------------------------------------------------------------------- */
/* Types                                                                       */
/* -------------------------------------------------------------------------- */

/**
 * Canonical slot family. Coarser than `schema.Slot` (there is one `ring`, not
 * `ring1..ring4`) because an item's capabilities do not depend on which of the
 * four ring slots it happens to sit in.
 */
export type CatalogueSlot =
	| 'weapon'
	| 'secondary'
	| 'emblem'
	| 'hat'
	| 'top'
	| 'bottom'
	| 'overall'
	| 'shoes'
	| 'gloves'
	| 'cape'
	| 'shoulder'
	| 'belt'
	| 'pendant'
	| 'ring'
	| 'earrings'
	| 'face'
	| 'eye'
	| 'pocket'
	| 'badge'
	| 'medal'
	| 'heart'
	| 'android'
	| 'totem';

export interface CatalogueEntry {
	id: number;
	name: string;
	slot: CatalogueSlot;
	/** The `ItemCategory` from `src/lib/schema/item.ts`. */
	category: string;
	/** REQ LEV / base item level. */
	itemLevel: number;
	/** In-game weapon-type label ("Two-Handed Sword", "Bow", "Claw", ...). */
	weaponType?: string;
	/** Occupies the secondary slot as well as the weapon slot. */
	twoHanded?: boolean;
	setItemId?: number;
	setName?: string;
	/**
	 * RAW WZ `tuc`. mapledoro's own `_meta` warns "in-game upgrade slots equal
	 * tuc plus 1" — we never display it, we only ask whether it is 0, which is
	 * the "this item has no upgrade slots at all" signal.
	 */
	upgradeSlots: number;
	iconUrl: string;

	canStarforce: boolean;
	fixedStarforce?: number;
	canFlame: boolean;
	canPotential: boolean;
	canBonusPotential: boolean;
	superior?: boolean;
	superiorMaxStars?: number;
	rules: string[];
}

export interface CatalogueMeta {
	generatedAt: string;
	region: string;
	gameVersion: string;
	minItemLevel: number;
	sources: Record<string, string>;
	counts: Record<string, number>;
}

export interface ItemCapabilities {
	canStarforce: boolean;
	canFlame: boolean;
	canPotential: boolean;
	canBonusPotential: boolean;
	/** Set when the item comes at a star count that cannot be changed (Genesis / Destiny = 22). */
	fixedStarforce?: number;
	/** Highest reachable star count. Absent when the item takes no star force at all. */
	maxStarforce?: number;
	superior?: boolean;
	/** False when the item name is not in the catalogue (permissive fallback was used). */
	known: boolean;
	/** The catalogue entries the name resolved to, in id order. Empty when unknown. */
	entries: readonly CatalogueEntry[];
	/** `{ ruleId: human-readable reason }` for every rule that fired. */
	reasons: Record<string, string>;
}

/** The subset of `schema.Item` this module needs. */
export interface CapabilityQuery {
	name: string;
	/** `ItemCategory` from the schema; used for the unknown-item fallback. */
	category?: string;
	/** `Slot` from the schema (`ring1`, `totem2`, ...); used for the unknown-item fallback. */
	slot?: string;
	itemLevel?: number;
	/** User-confirmed Tyrant/Nova/Elite Heliseum flag, if the catalogue does not know. */
	superior?: boolean;
}

/* -------------------------------------------------------------------------- */
/* The catalogue                                                               */
/* -------------------------------------------------------------------------- */

const doc = raw as unknown as CatalogueMeta & { entries: CatalogueEntry[] };

export const CATALOGUE: readonly CatalogueEntry[] = doc.entries;

export const CATALOGUE_META: CatalogueMeta = {
	generatedAt: doc.generatedAt,
	region: doc.region,
	gameVersion: doc.gameVersion,
	minItemLevel: doc.minItemLevel,
	sources: doc.sources,
	counts: doc.counts
};

/** Lowercase, whitespace-collapsed, punctuation-normalised item name. */
export function normalizeItemName(name: string): string {
	return name
		.normalize('NFKC')
		.replace(/[‘’ʼ]/g, "'")
		.replace(/[–—]/g, '-')
		.trim()
		.replace(/\s+/g, ' ')
		.toLowerCase();
}

const BY_NAME = new Map<string, CatalogueEntry[]>();
const BY_ID = new Map<number, CatalogueEntry>();
for (const entry of CATALOGUE) {
	BY_ID.set(entry.id, entry);
	const key = normalizeItemName(entry.name);
	const bucket = BY_NAME.get(key);
	if (bucket) bucket.push(entry);
	else BY_NAME.set(key, [entry]);
}

/** Every catalogue entry sharing an in-game name. Empty when the name is unknown. */
export function findByName(name: string): readonly CatalogueEntry[] {
	return BY_NAME.get(normalizeItemName(name)) ?? [];
}

export function findById(id: number): CatalogueEntry | undefined {
	return BY_ID.get(id);
}

/* -------------------------------------------------------------------------- */
/* Slot rules, for items the catalogue does not know                           */
/* -------------------------------------------------------------------------- */

/** `schema.Slot` (`ring1`, `totem2`, ...) -> `CatalogueSlot`. */
export function catalogueSlot(slot: string | undefined): CatalogueSlot | undefined {
	if (!slot) return undefined;
	const base = slot.replace(/\d+$/, '');
	if (base === 'pendant' || base === 'ring' || base === 'totem') return base as CatalogueSlot;
	return (
		[
			'weapon',
			'secondary',
			'emblem',
			'hat',
			'top',
			'bottom',
			'overall',
			'shoes',
			'gloves',
			'cape',
			'shoulder',
			'belt',
			'earrings',
			'face',
			'eye',
			'pocket',
			'badge',
			'medal',
			'heart',
			'android'
		] as const
	).find((s) => s === base);
}

/**
 * Slot families that never take star force, independent of any single item.
 * Verified against the v270 catalogue: every medal (316 at Lv100+), every
 * emblem, every pocket item, every totem, every android and every non-weapon
 * secondary has zero upgrade slots. Badges are ALMOST in this list — Ghost Ship
 * Exorcist and the Sengoku Hakase Badge are the only two that enhance — so
 * `badge` is deliberately absent and is decided per item instead.
 * Hearts / mechanical hearts DO take star force and are also absent.
 */
export const NEVER_STAR_FORCE_SLOTS: readonly CatalogueSlot[] = [
	'emblem',
	'medal',
	'pocket',
	'totem',
	'android'
];

/** formulas.md §4A §2.1. See `rules.ts` for the citation. */
export const NEVER_FLAME_SLOTS: readonly CatalogueSlot[] = [
	'secondary',
	'emblem',
	'badge',
	'medal',
	'ring',
	'android',
	'heart',
	'shoulder',
	'totem',
	'pocket'
];

/** formulas.md §4A §3.1. See `rules.ts` for the citation. */
export const NEVER_POTENTIAL_SLOTS: readonly CatalogueSlot[] = [
	'medal',
	'badge',
	'pocket',
	'android',
	'totem'
];

/* -------------------------------------------------------------------------- */
/* capabilities()                                                              */
/* -------------------------------------------------------------------------- */

/**
 * Per-item max-star exceptions that are NOT the Genesis/Destiny fixed-star
 * case. Taken from `starforce.MAX_STAR_EXCEPTIONS`, minus its `genesis` and
 * `destiny` rows: those match on a bare substring, which also captures the
 * Genesis Badge, the Genesis Bandana, the "Bond of Destiny" cape and four
 * "…Destiny" medals. The catalogue resolves the real weapons by id, so this
 * module handles them itself and only borrows the unambiguous rows.
 */
const NAMED_MAX_STAR_EXCEPTIONS = starforce.MAX_STAR_EXCEPTIONS.filter(
	(row) => !('fixed' in row && row.fixed)
);

function namedMaxStars(name: string): number | undefined {
	const lower = normalizeItemName(name);
	for (const row of NAMED_MAX_STAR_EXCEPTIONS) {
		if (lower.includes(row.match)) return row.maxStars;
	}
	return undefined;
}

/**
 * What this item can and cannot have done to it.
 *
 * Resolution order:
 *   1. Catalogue lookup by normalised name. If several entries share the name,
 *      capabilities are merged permissively (deny only when unanimous).
 *   2. If the name is unknown, fall back to the slot/category rules alone and
 *      flag `known: false`. This is deliberately permissive: an unrecognised
 *      item must still generate candidates, or a typo would silently delete a
 *      real upgrade from the ranking.
 */
export function capabilities(item: CapabilityQuery): ItemCapabilities {
	const entries = findByName(item.name);
	const ruleIds: string[] = [];

	const slot =
		entries.length > 0
			? entries[0].slot
			: (catalogueSlot(item.slot) ?? categoryToSlot(item.category));

	let canStarforce: boolean;
	let canFlame: boolean;
	let canPotential: boolean;
	let canBonusPotential: boolean;
	let fixedStarforce: number | undefined;
	let superior = item.superior === true;
	let superiorMaxStars: number | undefined;

	if (entries.length > 0) {
		// Permissive merge: deny only when every entry with this name denies.
		canStarforce = entries.some((e) => e.canStarforce);
		canFlame = entries.some((e) => e.canFlame);
		canPotential = entries.some((e) => e.canPotential);
		canBonusPotential = entries.some((e) => e.canBonusPotential);
		superior = superior || entries.some((e) => e.superior === true);

		const fixed = new Set(
			entries.map((e) => e.fixedStarforce).filter((v): v is number => v !== undefined)
		);
		if (fixed.size === 1 && entries.every((e) => e.fixedStarforce !== undefined)) {
			fixedStarforce = [...fixed][0];
		}

		const caps = entries
			.map((e) => e.superiorMaxStars)
			.filter((v): v is number => v !== undefined);
		if (caps.length > 0) superiorMaxStars = Math.max(...caps);

		for (const entry of entries) {
			for (const id of entry.rules) if (!ruleIds.includes(id)) ruleIds.push(id);
		}
		// A rule only earns its reason if it actually bit after the merge.
		if (canStarforce) {
			for (const id of ['no-upgrade-slots', 'liberated-weapon-fixed-star', 'destiny-stage-ambiguous']) {
				const at = ruleIds.indexOf(id);
				if (at >= 0) ruleIds.splice(at, 1);
			}
		}
		if (canFlame) drop(ruleIds, 'flame-ineligible-slot');
		if (canPotential) drop(ruleIds, 'potential-ineligible-slot');
	} else {
		ruleIds.push('unknown-item');
		canStarforce = slot === undefined || !NEVER_STAR_FORCE_SLOTS.includes(slot);
		canFlame = slot === undefined || !NEVER_FLAME_SLOTS.includes(slot);
		canPotential = slot === undefined || !NEVER_POTENTIAL_SLOTS.includes(slot);
		canBonusPotential = canPotential;
		if (!canStarforce) ruleIds.push('no-upgrade-slots');
		if (!canFlame) ruleIds.push('flame-ineligible-slot');
		if (!canPotential) ruleIds.push('potential-ineligible-slot');
	}

	// Bonus potential does not exist in Heroic — the only world scope modelled.
	if (canBonusPotential) ruleIds.push('bonus-potential-not-in-heroic');
	canBonusPotential = false;

	/* --- max stars -------------------------------------------------------- */
	const itemLevel = item.itemLevel ?? entries[0]?.itemLevel;
	let maxStarforce: number | undefined;
	if (fixedStarforce !== undefined) {
		maxStarforce = fixedStarforce;
	} else if (canStarforce && itemLevel !== undefined) {
		maxStarforce = starforce.maxStars(itemLevel, superior);
		const named = namedMaxStars(item.name);
		if (named !== undefined) maxStarforce = Math.min(maxStarforce, named);
		if (superiorMaxStars !== undefined) maxStarforce = Math.min(maxStarforce, superiorMaxStars);
	}

	return {
		canStarforce,
		canFlame,
		canPotential,
		canBonusPotential,
		...(fixedStarforce !== undefined ? { fixedStarforce } : {}),
		...(maxStarforce !== undefined ? { maxStarforce } : {}),
		...(superior ? { superior: true } : {}),
		known: entries.length > 0,
		entries,
		reasons: reasonsFor(ruleIds)
	};
}

function drop(ids: string[], id: string): void {
	const at = ids.indexOf(id);
	if (at >= 0) ids.splice(at, 1);
}

/** Last-resort slot guess from the schema `ItemCategory` when no slot was given. */
function categoryToSlot(category: string | undefined): CatalogueSlot | undefined {
	switch (category) {
		case 'weapon':
		case 'secondary':
		case 'emblem':
		case 'heart':
		case 'badge':
		case 'pocket':
		case 'medal':
		case 'android':
		case 'totem':
			return category;
		// `armor` and `accessory` span several slot families with different
		// rules (a ring takes no flames, a belt does), so there is nothing safe
		// to guess — return undefined and let the fallback stay permissive.
		default:
			return undefined;
	}
}

/** The single reason string for one rule id, for callers that want just the prose. */
export function ruleReason(id: RuleId): string {
	return RULES[id].reason;
}
