// Typed loader for the GMS 2026 boss dataset.
//
// The data lives in `bosses.json`, which is generated by `scripts/build-bosses.mjs`
// from docs/research/bosses.md (primary), kms-tools.md and existing-tools.md.
// Do not hand-edit the JSON — regenerate it.
//
// Conventions, restated from the JSON's own `_comment`:
//   * HEROIC ONLY. `crystal.solo` / `crystal.byPartySize` are Heroic (Reboot) payouts,
//     i.e. the bosses.md §1.6 listed price x5. The untouched listed prices are kept in
//     `crystal.nonHeroic`.
//   * `pdr` is a percentage (300 = 300%), NOT the 3.00 decimal factor the damage formula
//     wants. Divide by 100 at the call site.
//   * `cpGate` is the ChinaMS minimum Combat Power entry gate (bosses.md §3.2/§3.3). GMS
//     enforcement is unconfirmed (§3.1, §6.3) — treat it as advisory, never as a hard block.
//   * Any field a source did not supply is absent rather than estimated, so almost
//     everything is optional. `conflicts` records the cases where sources disagreed.

import raw from './bosses.json';

export type Difficulty = 'easy' | 'normal' | 'hard' | 'chaos' | 'extreme' | 'destiny' | 'champion';

export type ForceType = 'arcane' | 'sacred' | 'none';
export type Reset = 'daily' | 'weekly' | 'monthly';
export type Region = 'arcane-river' | 'grandis' | 'legacy';

export interface HpPhase {
	label: string;
	hp: number;
}

export interface BossHp {
	total: number;
	/**
	 * Per-phase / per-part HP where bosses.md §1.2 tabulates a split. Absent for the
	 * bosses whose parts share an HP bar or whose body entry auto-dies (§1.3) — those
	 * carry the explanation in `notes` instead.
	 */
	phases?: HpPhase[];
	note?: string;
}

export interface BossForce {
	type: ForceType;
	/** Force needed for the 100% damage band. Absent when `type` is `none`. */
	required?: number;
	/** Force at which the bonus caps: +50 for Sacred, 150% of `required` for Arcane (§4.5). */
	capAt?: number;
	/** Phase 2 requirement where it differs from phase 1 (§4.3: Normal Kalos, Chosen Seren). */
	phase2Required?: number;
	phase2CapAt?: number;
}

export interface BossCrystal {
	/** Heroic (Reboot) solo payout = bosses.md §1.6 listed value x5. */
	solo: number;
	/** Heroic payout per head at party sizes 1..6; `null` where that size cannot enter. */
	byPartySize: (number | null)[];
	heroicMultiplier: number;
	/** The untouched bosses.md §1.6 figures (regular worlds). */
	nonHeroic: { solo: number; byPartySize: (number | null)[] };
}

export interface BossCpGate {
	/** Total (or 1-person) minimum Combat Power (bosses.md §3.2). */
	solo?: number;
	/** Published per-member floors, keyed by party size. Sparse — see CP_PARTY_SIZE_RATIOS. */
	perMember?: Partial<Record<'2' | '3' | '4' | '5' | '6', number>>;
}

export interface BossScouter {
	/** MapleScouter solo cut in 환산 주스탯 units (kms-tools.md §2.4). */
	bossCut?: number;
	partyBossCut?: number;
	easyRate?: number;
	/** The boss PDR MapleScouter models, 300 or 380 (kms-tools.md §2.5). */
	guard?: number;
}

export interface BossConflict {
	field: string;
	chosen: number | string;
	chosenSource: string;
	alternatives: { value: number | string; source: string }[];
	note?: string;
}

export interface Boss {
	/** `${difficulty}-${boss}`, e.g. `hard-lucid`. */
	id: string;
	/** kebab-case boss family key, shared across difficulties. */
	boss: string;
	bossName: string;
	/** Only present where a source actually supplies it (bosses.md Appendix A). */
	nameKo?: string;
	difficulty: Difficulty;
	/** Monster level, which drives the level-difference damage penalty. */
	level?: number;
	/** Character level gate. */
	entryLevel?: number;
	hp?: BossHp;
	/** Physical Defense Rate as a percentage: 300 means 300%. */
	pdr?: number;
	force: BossForce;
	timeLimitMin?: number;
	deathCount?: number;
	/** Set instead of `deathCount` for bosses using a gauge (§1.2, Appendix B). */
	deathGauge?: string;
	partyMax?: number;
	reset?: Reset;
	crystal?: BossCrystal;
	cpGate?: BossCpGate;
	scouter?: BossScouter;
	/** Derived from `force.type`, not sourced — see the JSON `_comment`. */
	region: Region;
	sources: string[];
	notes?: string;
	conflicts?: BossConflict[];
}

export interface ExcludedBoss {
	name: string;
	nameKo?: string;
	reason: string;
}

export interface BossFile {
	generatedAt: string;
	server: string;
	sources: string[];
	notes: string[];
	excluded: ExcludedBoss[];
	bosses: Boss[];
}

const file = raw as unknown as BossFile;

/** Every boss x difficulty entry, in the order the source table lists them. */
export const BOSSES: readonly Boss[] = Object.freeze(file.bosses);

/** Bosses deliberately left out of `BOSSES`, with the reason. */
export const EXCLUDED: readonly ExcludedBoss[] = Object.freeze(file.excluded);

export const BOSS_DATA_SOURCES: readonly string[] = Object.freeze(file.sources);
export const BOSS_DATA_NOTES: readonly string[] = Object.freeze(file.notes);
export const BOSS_DATA_GENERATED_AT = file.generatedAt;

/**
 * bosses.md §3.3: across every boss with published per-party-size Combat Power floors the
 * per-member requirement is an essentially constant fraction of the solo requirement. Use
 * this only where `cpGate.perMember` has no real value for the party size — it is an
 * approximation, not game data.
 */
export const CP_PARTY_SIZE_RATIOS: Readonly<Record<number, number>> = Object.freeze({
	1: 1.0,
	2: 0.325,
	3: 0.215,
	4: 0.16,
	5: 0.13,
	6: 0.106
});

const BY_ID = new Map(BOSSES.map((b) => [b.id, b]));

/** Look up one entry by its `${difficulty}-${boss}` id. */
export function getBoss(id: string): Boss | undefined {
	return BY_ID.get(id);
}

/** Group entries by boss family key, preserving source order within each group. */
export function bossesByBoss(): Map<string, Boss[]> {
	const out = new Map<string, Boss[]>();
	for (const b of BOSSES) {
		const list = out.get(b.boss);
		if (list) list.push(b);
		else out.set(b.boss, [b]);
	}
	return out;
}

/**
 * The damage you must personally deal to receive loot: 5% of the boss's TOTAL HP
 * (bosses.md §2.2 — not 5% of the health bar currently showing). Returns `null` for
 * entries with no HP data (the Destiny / Champion mode variants).
 */
export function fivePercentHp(boss: Boss): number | null {
	return boss.hp ? boss.hp.total * 0.05 : null;
}

/**
 * The force requirement to reach the 100% damage band, or `null` when the boss has none.
 * Arcane and Sacred use completely different multiplier formulas (§4.1 vs §4.2) — branch
 * on `type`, never share a code path.
 */
export function forceRequirement(boss: Boss): { type: ForceType; required: number } | null {
	if (boss.force.type === 'none' || boss.force.required == null) return null;
	return { type: boss.force.type, required: boss.force.required };
}

/**
 * Entry ids ordered hardest -> easiest.
 *
 * The key is the CMS solo Combat Power gate (bosses.md §3.2), which is the only
 * cross-roster difficulty signal that is real client data. Entries with no published gate
 * (Akechi Mitsuhide, Ursus, Balrog, the Gollux tiers above Normal) fall back to monster
 * level and are appended after the ranked entries rather than interleaved, because CP and
 * level are not on a comparable scale. Ties break on level, then id, so the order is
 * deterministic.
 */
export const BOSS_ORDER: readonly string[] = Object.freeze(
	[...BOSSES]
		.sort((a, b) => {
			const ca = a.cpGate?.solo;
			const cb = b.cpGate?.solo;
			if (ca != null && cb != null && ca !== cb) return cb - ca;
			if (ca != null && cb == null) return -1;
			if (ca == null && cb != null) return 1;
			const la = a.level ?? -1;
			const lb = b.level ?? -1;
			if (la !== lb) return lb - la;
			return a.id.localeCompare(b.id);
		})
		.map((b) => b.id)
);
